#!/usr/bin/env bash

self_path="$(cd "$(dirname "$0")" >/dev/null 2>&1; pwd -P)"

urls=""
while IFS= read -r url; do
  fname="$("${self_path}/fname-from-url" <<<"${url}")"
  urls=$"${urls}\n${url} ${fname}"
done < "${1:-/dev/stdin}"

echo -e "${urls}" \
  | xargs -I{} sh -c 'curl -Lo "$(cut -d" " -f2 <<<"$1")" -C- "$(cut -d" " -f1 <<<"$1")"' -- {}

