#!/usr/bin/env python

import fileinput
from urllib.parse import urlparse
import sys


def filename_from_url(url: str) -> str:
    return urlparse(url).path.split('/')[-1]


def main():
    if not sys.stdin.isatty():
        for url in sys.stdin:
            print(filename_from_url(url))
    args = sys.argv[1:]
    if len(args) > 0:
        file_path = args[0]
        for url in open(file_path):
            print(filename_from_url(url))


if __name__ == '__main__':
    main()
